### ISSUE TITLE
provide a way to exclude AZ's

### ISSUE THREAD

**Issue by jaymccon** [taskcat/taskcat-v9#10] opened 2019-04-19 18:19 UTC
In some cases certain AZ's don't support some service features, or are capacity constrained, providing a config option to exclude specified AZ's from selection by the `taskcat_gen_azs_` function will allow users to work around these constraints.

**Comment by andrew-glenn** [comment] 2019-06-18 18:21
Duplicate of #18

**Closed by andrew-glenn** 2019-06-18 18:21 UTC
